FROM dunglas/frankenphp:1-php8.4-alpine

RUN install-php-extensions pdo_pgsql

WORKDIR /app

COPY . .

COPY Caddyfile /etc/caddy/Caddyfile

RUN chown -R www-data:www-data /app

USER www-data

ENV PORT=80

EXPOSE 80

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
